import pandas as pd

def filter_questions(input_file, output_file):
    '''
    input_file - str - path to axios-ipsos covid survey
    output_file - str - path to output file

    it simply keeps the columns named in "columns_to_keep" and deletes all other columns
    '''
    print(input_file)
    df = pd.read_csv(input_file, encoding="ISO-8859-1")
    
    columns_to_keep = [
    "wt_final", "Q107_1", "Q107_2", "Q107_3", "Q107_4", "ppreg4", "ppmsacat", 
    "ppeducat","ppinc7", "ppgender", "ppmarit5", 
    "pphhsize", "pprent", "ppethm"
    ]
    #"ppinc7"
    # Filter the DataFrame to keep only the specified columns
    df_filtered = df[columns_to_keep]
    # Save the cleaned data
    df_filtered.to_csv(output_file, index=False, encoding="ISO-8859-1")
    print(f"Filtered data saved to {output_file}")

def recoding_survey_and_census_data(survey_df, census_df):

    '''
    survey_df - pandas df - IPUMS survey data dataframe
    census_df - pandas df - AXIOS-Ipsos covid index survey data dataframe

    iterates over a survey df and census df and re-encodes all variables manually

    reincoding code was generated by CHATGPT
    '''
    if survey_df is not None:
        region_mapping_survey = {
        'MidWest': 1,
        'South': 2,
        'West': 3,
        'NorthEast': 4
        }

        # Recode the region column in the survey data
        survey_df['ppreg4'] = survey_df['ppreg4'].map(region_mapping_survey)

        
        # Define a mapping for the ppmsacat values
        ppmsacat_mapping = {
            'Metro': 1,      # In metropolitan area
            'Non-Metro': 0   # Not in metropolitan area
        }

        # Recode the ppmsacat column in the survey data
        survey_df['ppmsacat'] = survey_df['ppmsacat'].map(ppmsacat_mapping)
        
        #income
        ppinc7_mapping = {
        'Less than $5,000': 1,
        '$5,000 to $7,499': 2,
        '$7,500 to $9,999': 2,
        '$10,000 to $12,499': 3,
        '$12,500 to $14,999': 3,
        '$15,000 to $19,999': 4,
        '$20,000 to $24,999': 5,
        '$25,000 to $29,999': 6,
        '$30,000 to $34,999': 7,
        '$35,000 to $39,999': 8,
        '$40,000 to $49,999': 9,
        '$50,000 to $59,999': 10,
        '$60,000 to $74,999': 11,
        '$75,000 to $84,999': 12,
        '$85,000 to $99,999': 13,
        '$100,000 to $124,999': 14,
        '$125,000 to $149,999': 15,
        '$150,000 to $174,999': 16,
        '$175,000 to $199,999': 17,
        '$200,000 to $249,999': 18,
        '$250,000 or more': 19
        }
        
        survey_df['ppinc7'] = survey_df['ppinc7'].map(ppinc7_mapping)

        #gender only need to do survey
        gender_mapping = {'Male': 1, 'Female':2}

        survey_df['ppgender'] = survey_df['ppgender'].map(gender_mapping)

        #marital status
        ppmarit5_mapping = {
        'Married': 1,
        'Separated': 2,
        'Divorced': 3,
        'Widowed': 4,
        'Never married': 5,
        'Living with partner': 0
        }

        # Recode the ppmarit5 column in the survey data
        survey_df['ppmarit5'] = survey_df['ppmarit5'].map(ppmarit5_mapping)

        #family size survey
        pphhsize_mapping = {
        '1': 1,
        '2': 2,
        '3': 3,
        '4': 4,
        '5': 5,
        '6 or more': 6
        }

        # Recode the pphhsize column in the survey data
        survey_df['pphhsize'] = survey_df['pphhsize'].map(pphhsize_mapping)

        #race survey
        ppethm_mapping = {
        'White, Non-Hispanic': 1,
        'Black, Non-Hispanic': 2,
        'Hispanic': 3,
        'Other, Non-Hispanic': 4,
        '2+ Races, Non-Hispanic': 5
        }
        survey_df['ppethm'] = survey_df['ppethm'].map(ppethm_mapping)
        
         #educat
        ppeducat_mapping = {
        'Bachelors degree or higher': 4,
        'Some college': 3,
        'High school': 2,
        'Less than high school': 1
        }

        # Recode the ppeducat column in the survey data
        survey_df['ppeducat'] = survey_df['ppeducat'].map(ppeducat_mapping)
        
        #vaccine
        vaccine_mapping = {
            'Yes, I have received the vaccine': 1,
            'Skipped': 0
        }
        survey_df['VACCINED'] = ""    
        survey_df['VACCINED'] = survey_df['Q107_1'].map(vaccine_mapping)
        
    if census_df is not None:
        def recode_census_region(value):
            if 10 <= value <= 19:
                return 4  # NorthEast
            elif 20 <= value <= 29:
                return 1  # MidWest
            elif 30 <= value <= 39:
                return 2  # South
            elif 40 <= value <= 49:
                return 3  # West
            else:
                return None  # Handle unexpected values
        # Apply the recoding function to the region column in the census data
        census_df['REGION'] = census_df['REGION'].apply(recode_census_region)


        # Define a function to recode METRO values
        def recode_metro(value):
            if value in [2, 3, 4]:
                return 1  # In metropolitan area
            elif value == 1:
                return 0  # Not in metropolitan area
            elif value == 0:
                return None  # Metropolitan status indeterminable (can be dropped or handled separately)
            else:
                return None  # Handle unexpected values

        # Apply the recoding function to the METRO column in the census data
        census_df['METRO'] = census_df['METRO'].apply(recode_metro)

    

        income_buckets = [
        (0, 4999, 1),
        (5000, 9999, 2),
        (10000, 14999, 3),
        (15000, 19999, 4),
        (20000, 24999, 5),
        (25000, 29999, 6),
        (30000, 34999, 7),
        (35000, 39999, 8),
        (40000, 49999, 9),
        (50000, 59999, 10),
        (60000, 74999, 11),
        (75000, 84999, 12),
        (85000, 99999, 13),
        (100000, 124999, 14),
        (125000, 149999, 15),
        (150000, 174999, 16),
        (175000, 199999, 17),
        (200000, 249999, 18),
        (250000, float('inf'), 19)
        ]

        def assign_bucket_number(income):
            for lower, upper, bucket_number in income_buckets:
                if lower <= income <= upper:
                    return bucket_number
            return None  # For values outside the defined buckets
        # Apply the function to the INCTOT column
        # Use .loc to explicitly assign values to the DataFrame
        c_copy = census_df.copy()
        census_df['INCTOT'] = c_copy['INCTOT'].apply(assign_bucket_number)
        del c_copy

        #survey marital
        marst_mapping = {
        1: 1,  # Married, spouse present → Married
        2: 1,  # Married, spouse absent → Married
        3: 2,  # Separated → Separated
        4: 3,  # Divorced → Divorced
        5: 4,  # Widowed → Widowed
        6: 5   # Never married/single → Never married/single
        }

        # Recode the MARST column in the census data
        census_df['MARST'] = census_df['MARST'].map(marst_mapping)
        #family size census
        def recode_famsize(size):
            if size >= 6:
                return 6  # '6 or more'
            else:
                return size  # Keep values 1-5 as is

        # Apply the recoding function to the FAMSIZE column
        census_df['FAMSIZE'] = census_df['FAMSIZE'].apply(recode_famsize)

    

        #race census
        race_mapping = {
        1: 1,  # White → 1
        2: 2,  # Black/African American → 2
        3: 4,  # American Indian or Alaska Native → 4 (Other, Non-Hispanic)
        4: 4,  # Chinese → 4 (Other, Non-Hispanic)
        5: 4,  # Japanese → 4 (Other, Non-Hispanic)
        6: 4,  # Other Asian or Pacific Islander → 4 (Other, Non-Hispanic)
        7: 4,  # Other race, nec → 4 (Other, Non-Hispanic)
        8: 5,  # Two major races → 5 (2+ Races, Non-Hispanic)
        9: 5   # Three or more major races → 5 (2+ Races, Non-Hispanic)
        }
        census_df['RACE'] = census_df['RACE'].map(race_mapping)

        educ_mapping = {
        0: 1,  # N/A or no schooling → Less than high school
        1: 1,  # Nursery school to grade 4 → Less than high school
        2: 1,  # Grade 5, 6, 7, or 8 → Less than high school
        3: 1,  # Grade 9 → Less than high school
        4: 1,  # Grade 10 → Less than high school
        5: 1,  # Grade 11 → Less than high school
        6: 2,  # Grade 12 → High school
        7: 3,  # 1 year of college → Some college
        8: 3,  # 2 years of college → Some college
        9: 3,  # 3 years of college → Some college
        10: 4,  # 4 years of college → Bachelors degree or higher
        11: 4   # 5+ years of college → Bachelors degree or higher
        }

        # Recode the EDUC column in the census data
        census_df['EDUC'] = census_df['EDUC'].map(educ_mapping)