BATCH_SIZE: 2
SUBSET_SIZE: 32 #mini-batch size
GENERATOR_TRAINING_FACTOR: 1
DISCRIMINATOR_TRAINING_FACTOR: 8
DEVICE : "cuda:0"
week: [29] #the week ID for HHP
BATCHS_IN_EPOCH: 1
EPOCHS: 1
NUM_TRIALS: 1


GT_LIMIT: 50000
BIAS_LIMIT: &bias_limit 2500

SAVE_DICT:
  SAVE_IG: true
  SAVE_DATASET: true
  SAVE_WEIGHTS: true
  SAVE_GENERATOR: false
  SAVE_CRITIC: false
  SAVE_EVERY: -1  # -1 means only save the last one

KLIEP_DOWNSAMPLE: *bias_limit  # equals BIAS_LIMIT

LAMBDAGP: 10            # higher = less discriminator expressability
LAMBDAW: 0.00075        # .00075 for 10k .006 for 2.5k
LAMBDAD: 13.5
LAMBDA_FIRST_LAYER: 0

GENERATOR_LEARNING_RATE: 1.0e-5
DISCRIMINATOR_LEARNING_RATE: 5.0e-5

GEN_HISTORY_LENGTH: 0
WARMUP_EPOCHS: 0
GEN_LAYERS: [1024, 1024, 1024]
DISC_LAYERS: [256, 256]

GEN_DROPOUT: 0.2
DISC_DROPOUT: 0.2

TEMPERATURE_START: 1
TEMPERATURE_END: 0.3
TEMPERATURE: 1

DEBUG_MODE: false

SAME_DATA_GT: false
SAME_DATA_BIAS: false
SAME_DATA_SEEN: false
SAME_NETWORK_INIT: true


