import pandas as pd
import os
import random

def filter_questions(input_file, output_file):
    '''
    input_file - str - path to axios-ipsos covid survey
    output_file - str - path to output file

    it simply keeps the columns named in "columns_to_keep" and deletes all other columns
    '''
    print(input_file)
    df = pd.read_csv(input_file, encoding="ISO-8859-1")
    
    columns_to_keep = [
    "wt_final", "Q107_1", "Q107_2", "Q107_3", "Q107_4", "ppreg4", "ppmsacat", 
    "ppeducat","ppinc7", "ppgender", "ppmarit5", 
    "pphhsize", "pprent", "ppethm"
    ]
    #"ppinc7"
    # Filter the DataFrame to keep only the specified columns
    df_filtered = df[columns_to_keep]
    # Save the cleaned data
    df_filtered.to_csv(output_file, index=False, encoding="ISO-8859-1")
    print(f"Filtered data saved to {output_file}")

def recoding_survey_and_census_data(survey_df, census_df, target_var):

    '''
    survey_df - pandas df - household census survey data
    census_df - pandas df - IPUMS survey 
    iterates over a survey df and census df and re-encodes all variables manually
    target_var - list[str] of target variable names

    reincoding code was generated by CHATGPT
    '''
    state_code_to_biden_pct = {
        1: 0.3657,
        2: 0.4277,
        4: 0.4936,
        5: 0.3478,
        6: 0.6348,
        8: 0.5540,
        9: 0.5924,
        10: 0.5878,
        11: 0.9215,
        12: 0.4786,
        13: 0.4950,
        15: 0.6373,
        16: 0.3307,
        17: 0.5754,
        18: 0.4096,
        19: 0.4489,
        20: 0.4156,
        21: 0.3615,
        22: 0.3985,
        23: 0.5309,
        24: 0.6536,
        25: 0.6560,
        26: 0.5062,
        27: 0.5240,
        28: 0.4106,
        29: 0.4141,
        30: 0.4055,
        31: 0.3936,
        32: 0.5006,
        33: 0.5271,
        34: 0.5733,
        35: 0.5429,
        36: 0.6086,
        37: 0.4859,
        38: 0.3176,
        39: 0.4524,
        40: 0.3229,
        41: 0.5645,
        42: 0.5001,
        44: 0.5939,
        45: 0.4343,
        46: 0.3561,
        47: 0.3745,
        48: 0.4648,
        49: 0.3765,
        50: 0.6609,
        51: 0.5411,
        53: 0.5797,
        54: 0.2970,
        55: 0.4945,
        56: 0.2655
    }
    
    #drop all columns not prevelant to each survey
    YEAR = 2021
    relevant_columns_global = ['REGION', 'EDUC', 'INCTOT', 'SEX', 'MARST', 'RACE', 'AGE']
    #target_var = 'RECVDVACC' or HLTHINS1
    if survey_df is not None:
        nan_check = target_var + ['REGION', 'EEDUC', 'INCOME', 'EGENDER', 'MS', 'RRACE', 'TBIRTH_YEAR']
        survey_df = survey_df.dropna(subset=nan_check)
        
        #remove people that didnt answer vaccine question
        for var in nan_check:
            survey_df = survey_df[survey_df[var] != -99]
            survey_df = survey_df[survey_df[var] != -88]

        #remove all people that got an associates degree. this info is not tracked by ipums
        survey_df= survey_df[survey_df['EEDUC'] != 5]

        survey_df['EST_ST'] = survey_df['EST_ST'].map(state_code_to_biden_pct)

        def recode_recieved_vaccine(value):
            if value == 2: #no
                return 0
            elif value == 1: #yes
                return 1
        for target_col in target_var:
            survey_df[target_col] = survey_df[target_col].apply(recode_recieved_vaccine)
        
        def recode_census_age(value):
            if YEAR - value >= 85: 
                return 5
            elif YEAR - value >= 65:
                return 4
            elif YEAR - value >= 50:
                return 3
            elif YEAR - value >= 35:
                return 2
            elif YEAR - value >= 18:
                return 1
        survey_df['TBIRTH_YEAR'] = survey_df['TBIRTH_YEAR'].apply(recode_census_age)

        #region. dont have to do anything i think

        #education
        education_mapping = {
            1: 1,  # Less than high school
            2: 1,  # Less than high school
            3: 2,  # High school graduate
            4: 3,  # Some college
            6: 4,  # Bachelor’s degree
            7: 5   # Graduate degree
        }
        survey_df['EEDUC'] = survey_df['EEDUC'].map(education_mapping)

        #ipums chosen variables: REGION,EDUC,INCTOT,SEX,MARST,FAMSIZE,RACE, BIRTHYR
        #census corresponding: REGION, EEDUC, INCOME, EGENDER, MS, THHLD_NUMPER, RRACE, TBIRTH_YEAR

        #TBIRTH_YEAR just rename to AGE
        survey_df.rename(columns={'TBIRTH_YEAR':'AGE'},inplace=True)

        #RRACE just rename to RACE
        survey_df.rename(columns={'RRACE':'RACE'},inplace=True)

        #INCOME just rename to INCTOT
        survey_df.rename(columns={'INCOME':'INCTOT'},inplace=True)

        #EEDUC just rename to EDUC
        survey_df.rename(columns={'EEDUC':'EDUC'},inplace=True)

        #EGENDER just rename to sex
        survey_df.rename(columns={'EGENDER':'SEX'},inplace=True)

        #marital status the census is re-encoded to match
        survey_df.rename(columns={'MS':'MARST'},inplace=True)

        #household size: THHLD_NUMPER nothing to do but rename
        survey_df.rename(columns={'THHLD_NUMPER':'FAMSIZE'},inplace=True)
        
        #state ID rename to biden vote %
        survey_df.rename(columns={'EST_ST':'BIDENPERC'},inplace=True)
        
        relevant_columns_local = target_var + relevant_columns_global

        #deleting famsize because the categories are too different
        survey_df = survey_df.filter(items=relevant_columns_local)

    if census_df is not None:
        #remove anyone with GQ != 1
        census_df = census_df[census_df['GQ'] == 1]
        #clean any missing birth years
        census_df = census_df[~census_df['BIRTHYR'].isin([9996,9997,9998,9999])]
        #remove anyone with birthyear born within 18 years of survey.
        census_df = census_df[YEAR - census_df['BIRTHYR'] >= 18]
        #remove anyone with family size over 40
        census_df = census_df[census_df['FAMSIZE']<=40]
        #sex clean up missing values
        census_df= census_df[census_df['SEX'] != 9] 
        #education. remove missing entries before mapping
        census_df = census_df[census_df['EDUC'] != 99] 

        census_df['STATEFIP'] = census_df['STATEFIP'].map(state_code_to_biden_pct)

        # REGION,EDUC,INCTOT,SEX,MARST,FAMSIZE,RACE,BIRTHYR
        def recode_census_age(value):
            if YEAR - value >= 85: 
                return 5
            elif YEAR - value >= 65:
                return 4
            elif YEAR - value >= 50:
                return 3
            elif YEAR - value >= 35:
                return 2
            elif YEAR - value >= 18:
                return 1
        census_df['BIRTHYR'] = census_df['BIRTHYR'].apply(recode_census_age)

        def recode_census_region(value):
            if 10 <= value <= 19:
                return 1  # NorthEast
            elif 20 <= value <= 29:
                return 3  # MidWest
            elif 30 <= value <= 39:
                return 2  # South
            elif 40 <= value <= 49:
                return 4  # West
            else:
                return None  # Handle unexpected values
        # Apply the recoding function to the region column in the census data
        census_df['REGION'] = census_df['REGION'].apply(recode_census_region)


        def map_income(value):
            if value == -99:
                return -99  # Question seen but not selected
            elif value == -88:
                return -88  # Missing / Did not report
            elif value < 25000:
                return 1  # Less than $25,000
            elif 25000 <= value < 35000:
                return 2  # $25,000 - $34,999
            elif 35000 <= value < 50000:
                return 3  # $35,000 - $49,999
            elif 50000 <= value < 75000:
                return 4  # $50,000 - $74,999
            elif 75000 <= value < 100000:
                return 5  # $75,000 - $99,999
            elif 100000 <= value < 150000:
                return 6  # $100,000 - $149,999
            elif 150000 <= value < 200000:
                return 7  # $150,000 - $199,999
            else:
                return 8  # $200,000 and above

        census_df['INCTOT'] = census_df['INCTOT'].apply(map_income)

        #survey marital
        marital_status_map = {
            1: 1,  # Married, spouse present -> Now married
            2: 1,  # Married, spouse absent -> Now married
            3: 4,  # Separated -> Separated
            4: 3,  # Divorced -> Divorced
            5: 2,  # Widowed -> Widowed
            6: 5   # Never married/single -> Never married
        }

        # Recode the MARST column in the census data
        census_df['MARST'] = census_df['MARST'].map(marital_status_map)

        #race census
        race_map = {
            1: 1,  # White -> White, Alone
            2: 2,  # Black/African American -> Black, Alone
            3: 4,  # American Indian or Alaska Native -> Any other race alone, or race in combination
            4: 3,  # Chinese -> Asian, Alone
            5: 3,  # Japanese -> Asian, Alone
            6: 3,  # Other Asian or Pacific Islander -> Asian, Alone
            7: 4,  # Other race, nec -> Any other race alone, or race in combination
            8: 4,  # Two major races -> Any other race alone, or race in combination
            9: 4   # Three or more major races -> Any other race alone, or race in combination
        }
        census_df['RACE'] = census_df['RACE'].map(race_map)

        educ_mapping = {
            0: 1,  # N/A or no schooling
            1: 1,  # Less than high school
            2: 1,  # Less than high school
            3: 1,  # Less than high school
            4: 1,  # Less than high school
            5: 1,  # Less than high school
            6: 2,  # High school graduate
            7: 3,  # Some college
            8: 3,  # Some college
            9: 3,  # Some college
            10: 4, # Bachelor's degree
            11: 5  # Graduate degree
        }

        # Recode the EDUC column in the census data
        census_df['EDUC'] = census_df['EDUC'].map(educ_mapping)

        #BIRTHYEAR just rename to AGE
        census_df.rename(columns={'BIRTHYR':'AGE'},inplace=True)

        #state ID rename to biden vote %
        census_df.rename(columns={'STATEFIP':'BIDENPERC'},inplace=True)

        relevant_columns_local = ['PERWT'] + relevant_columns_global
        #REGION,EDUC,INCTOT,SEX,MARST,FAMSIZE,RACE, BIRTHYR
        #deleting famsize because the categories are too different and BIDENPERC
        census_df = census_df.filter(items=relevant_columns_local)

    return survey_df, census_df

def load_evenly_sampled_csv_rows(directory_path, K, target_var):
    # Get list of CSV files in the directory
    csv_files = [f for f in os.listdir(directory_path) if f.endswith(".csv")]
    num_files = len(csv_files)
    
    if num_files == 0:
        raise ValueError("No CSV files found in the directory.")
    
    # Determine how many rows to sample from each file
    base_rows = K // num_files
    remainder = K % num_files  # Distribute leftover rows evenly

    sampled_rows = []

    for i, csv_file in enumerate(csv_files):
        file_path = os.path.join(directory_path, csv_file)
        df = pd.read_csv(file_path)
        
        if "EGENID_BIRTH" in df.columns:
            df = df.rename(columns={"EGENID_BIRTH": "EGENDER"})
            
        nan_check = [target_var, 'REGION', 'EEDUC', 'INCOME', 'EGENDER', 'MS', 'RRACE', 'TBIRTH_YEAR', ]
        df = df.dropna(subset=nan_check)

        if df.empty:
            continue  # Skip empty files

        # Determine how many rows to sample from this file
        n_rows = base_rows + (1 if i < remainder else 0)
        n_rows = min(n_rows, len(df))  # Don't exceed available rows

        sampled_df = df.sample(n=n_rows, random_state=random.randint(0, 10000))
        sampled_rows.append(sampled_df)

    # Concatenate all sampled dataframes
    combined_df = pd.concat(sampled_rows, ignore_index=True)
    
    # If we sampled fewer rows than K due to small CSVs, fill in extra from any available data
    while len(combined_df) < K:
        for csv_file in csv_files:
            if len(combined_df) >= K:
                break
            file_path = os.path.join(directory_path, csv_file)
            df = pd.read_csv(file_path)
            if df.empty:
                continue
            remaining_rows = df[~df.index.isin(sampled_df.index)]
            if not remaining_rows.empty:
                extra_row = remaining_rows.sample(n=1, random_state=random.randint(0, 10000))
                combined_df = pd.concat([combined_df, extra_row], ignore_index=True)

    return combined_df.head(K)

if __name__ == "__main__":
    pass