import pandas as pd

def recoding_survey_and_census_data(survey_df, census_df):

    '''
    survey_df - pandas df - household census survey data
    census_df - pandas df - IPUMS survey 
    iterates over a survey df and census df and re-encodes all variables manually

    reincoding code was generated by CHATGPT
    '''
    #drop all columns not prevelant to each survey
    relevant_columns_global = ['REGION', 'EDUC', 'SEX', 'MARST', 'RACE']
    
    if survey_df is not None:
        #get rid of uncessary columns
        vars_to_keep = ['employmentstatus', 'location', 'education', 'sex', 'maritalstatus', 'raceethnicity', 'age']
        survey_df = survey_df[vars_to_keep]
        #clean employment column
        accepted_answers = ['Full-time', 'Retired', 'Part-time', 'Unemployed', 'Homemaker', 'Permanently disabled',
                            'Student', 'Other, please specify:', 'Temporarily laid off']
        survey_df = survey_df[survey_df['employmentstatus'].isin(accepted_answers)]

        #clean up sex attribute
        accepted_sex_values = ['Male', 'Female']
        survey_df = survey_df[survey_df['sex'].isin(accepted_sex_values)]

        #clean up region
        bad_region_mask = []
        for r in survey_df['location']:
            if not isinstance(r, str):
                bad_region_mask.append(False)
            elif r == 'JB' or r == 'FC':
                bad_region_mask.append(False)
            else:
                bad_region_mask.append(True)
        survey_df = survey_df[bad_region_mask]

        def recode_sex(value):
            if value == 'Female':
                return 2
            else:
                return 1
    
        def recode_age(value):
            value = int(value)
            if value >= 85: 
                return 5
            elif value >= 65:
                return 4
            elif value >= 50:
                return 3
            elif value >= 35:
                return 2
            elif value >= 18:
                return 1
            else:
                return -1 #invalid ages, 16 and 17 mostly

        base_race_answers = ['White For example, German, Irish, English, Italian, Polish, French, etc.',
                            'Black or African American For example, African American, Jamaican, Haitian, Nigerian, Ethiopian, Somali, etc.',
                            'Hispanic or Latino For example, Mexican or Mexican American, Puerto Rican, Cuban, Salvadoran, Dominican, Colombian, etc.',
                            'Asian For example, Chinese, Filipino, Asian Indian, Vietnamese, Korean, Japanese, etc.',
                            'American Indian or Alaskan Native For example, Navajo Nation, Blackfeet Tribe, Mayan, Aztec, Native Village of Barrow Inupiat Tribal Government, Tlingit, etc.',
                            'Native Hawaiian or Pacific Islander For example, Native Hawaiian, Samoan, Chamorro, Tongan, Fijian, Marshallese, etc.',
                            'Middle Eastern or North African For example, Lebanese, Iranian, Egyptian, Syrian, Moroccan, Israeli, etc.']

        def encode_race(value):
            num_races = 0
            for ba in base_race_answers:
                if ba in value:
                    num_races += 1
            if num_races == 1:
                if value == 'White For example, German, Irish, English, Italian, Polish, French, etc.':
                    return 1
                elif value == 'Black or African American For example, African American, Jamaican, Haitian, Nigerian, Ethiopian, Somali, etc.':
                    return 2
                elif value == 'American Indian or Alaskan Native For example, Navajo Nation, Blackfeet Tribe, Mayan, Aztec, Native Village of Barrow Inupiat Tribal Government, Tlingit, etc.':
                    return 4
                elif value == 'Asian For example, Chinese, Filipino, Asian Indian, Vietnamese, Korean, Japanese, etc.':
                    return 3
                elif value == 'American Indian or Alaskan Native For example, Navajo Nation, Blackfeet Tribe, Mayan, Aztec, Native Village of Barrow Inupiat Tribal Government, Tlingit, etc.':
                    return 4
                elif value == 'Native Hawaiian or Pacific Islander For example, Native Hawaiian, Samoan, Chamorro, Tongan, Fijian, Marshallese, etc.':
                    return 3
                else:
                    return 4
            else:
                return 4

        marital_status_map = {
                    'Now married': 1,  # Married, spouse present -> Now married
                    'Separated': 4,  # Separated -> Separated
                    'Divorced': 3,  # Divorced -> Divorced
                    'Widowed': 2,  # Widowed -> Widowed
                    'Never married': 5   # Never married/single -> Never married
                }


        educ_mapping = {
            'Less than high school': 1,  # N/A or no schooling
            'Some high school': 1,
            'High school graduate or equivalent (for example GED)': 2,  # High school graduate
            'Some college, but degree not received or is in progress': 3,  # Some college
            'Associate\'s degree (for example AA, AS)': 3,  # Some college
            'Bachelor\'s degree (for example BA, BS, AB)': 4, # Bachelor's degree
            'Graduate degree (for example master\'s, professional, doctorate)': 5  # Graduate degree
        }

        def get_region_id(state_abbr):
            region_mapping = {
                # Region 1: Northeast
                'CT': 1, 'ME': 1, 'MA': 1, 'NH': 1, 'RI': 1, 'VT': 1,
                'NJ': 1, 'NY': 1, 'PA': 1,

                # Region 2: Midwest
                'IL': 2, 'IN': 2, 'MI': 2, 'OH': 2, 'WI': 2,
                'IA': 2, 'KS': 2, 'MN': 2, 'MO': 2, 'NE': 2, 'ND': 2, 'SD': 2,

                # Region 3: South
                'DE': 3, 'DC': 3, 'FL': 3, 'GA': 3, 'MD': 3,
                'NC': 3, 'SC': 3, 'VA': 3, 'WV': 3,
                'AL': 3, 'KY': 3, 'MS': 3, 'TN': 3,
                'AR': 3, 'LA': 3, 'OK': 3, 'TX': 3,

                # Region 4: West
                'AZ': 4, 'CO': 4, 'ID': 4, 'MT': 4, 'NV': 4, 'NM': 4, 'UT': 4, 'WY': 4,
                'AK': 4, 'CA': 4, 'HI': 4, 'OR': 4, 'WA': 4
            }
            return region_mapping.get(state_abbr, None)
        
        def encode_employment(value):
            if value == 'Full-time' or value == 'Part-time':
                return 1
            else:
                return 0
        
        survey_df['sex'] = survey_df['sex'].apply(recode_sex)
        survey_df['age'] = survey_df['age'].apply(recode_age)
        survey_df = survey_df[survey_df['age'] != -1]

        survey_df['employmentstatus'] = survey_df['employmentstatus'].apply(encode_employment)
        survey_df = survey_df.dropna(subset=['raceethnicity'])
        survey_df['raceethnicity'] = survey_df['raceethnicity'].apply(encode_race)
        # Recode the MARST column in the census data
        survey_df = survey_df.dropna(subset=['maritalstatus'])
        survey_df['maritalstatus'] = survey_df['maritalstatus'].map(marital_status_map)
        survey_df['education'] = survey_df['education'].map(educ_mapping)
        #survey_df = survey_df.dropna(subset=['education'])
        survey_df['location'] = survey_df['location'].apply(get_region_id)

        #ipums chosen variables: REGION,EDUC,INCTOT,SEX,MARST,FAMSIZE,RACE, BIRTHYR
        #census corresponding: REGION, EEDUC, INCOME, EGENDER, MS, THHLD_NUMPER, RRACE, TBIRTH_YEAR

        #TBIRTH_YEAR just rename to AGE
        survey_df.rename(columns={'age':'AGE'},inplace=True)

        #RRACE just rename to RACE
        survey_df.rename(columns={'raceethnicity':'RACE'},inplace=True)

        #EEDUC just rename to EDUC
        survey_df.rename(columns={'education':'EDUC'},inplace=True)

        #EGENDER just rename to sex
        survey_df.rename(columns={'sex':'SEX'},inplace=True)

        #marital status the census is re-encoded to match
        survey_df.rename(columns={'maritalstatus':'MARST'},inplace=True)

        #location -> Region
        survey_df.rename(columns={'location':'REGION'},inplace=True)
        
        relevant_survey_col = ['employmentstatus'] + relevant_columns_global

        survey_df = survey_df.filter(items=relevant_survey_col)

    if census_df is not None:
        YEAR = 2023
        #remove anyone with GQ != 1
        census_df = census_df[census_df['GQ'] == 1]
        #clean any missing birth years
        census_df = census_df[~census_df['BIRTHYR'].isin([9996,9997,9998,9999])]
        #remove anyone with birthyear born within 18 years of survey.
        census_df = census_df[YEAR - census_df['BIRTHYR'] >= 18]
        #remove anyone with family size over 40
        census_df = census_df[census_df['FAMSIZE']<=40]
        #sex clean up missing values
        census_df= census_df[census_df['SEX'] != 9] 
        #education. remove missing entries before mapping
        census_df = census_df[census_df['EDUC'] != 99] 

        # REGION,EDUC,INCTOT,SEX,MARST,FAMSIZE,RACE,BIRTHYR
        def recode_census_age(value):
            if YEAR - value >= 85: 
                return 5
            elif YEAR - value >= 65:
                return 4
            elif YEAR - value >= 50:
                return 3
            elif YEAR - value >= 35:
                return 2
            elif YEAR - value >= 18:
                return 1
        census_df['BIRTHYR'] = census_df['BIRTHYR'].apply(recode_census_age)

        def recode_census_region(value):
            if 10 <= value <= 19:
                return 1  # NorthEast
            elif 20 <= value <= 29:
                return 3  # MidWest
            elif 30 <= value <= 39:
                return 2  # South
            elif 40 <= value <= 49:
                return 4  # West
            else:
                return None  # Handle unexpected values
        # Apply the recoding function to the region column in the census data
        census_df['REGION'] = census_df['REGION'].apply(recode_census_region)


        def map_income(value):
            if value == -99:
                return -99  # Question seen but not selected
            elif value == -88:
                return -88  # Missing / Did not report
            elif value < 25000:
                return 1  # Less than $25,000
            elif 25000 <= value < 35000:
                return 2  # $25,000 - $34,999
            elif 35000 <= value < 50000:
                return 3  # $35,000 - $49,999
            elif 50000 <= value < 75000:
                return 4  # $50,000 - $74,999
            elif 75000 <= value < 100000:
                return 5  # $75,000 - $99,999
            elif 100000 <= value < 150000:
                return 6  # $100,000 - $149,999
            elif 150000 <= value < 200000:
                return 7  # $150,000 - $199,999
            else:
                return 8  # $200,000 and above

        census_df['INCTOT'] = census_df['INCTOT'].apply(map_income)

        #survey marital
        marital_status_map = {
            1: 1,  # Married, spouse present -> Now married
            2: 1,  # Married, spouse absent -> Now married
            3: 4,  # Separated -> Separated
            4: 3,  # Divorced -> Divorced
            5: 2,  # Widowed -> Widowed
            6: 5   # Never married/single -> Never married
        }

        # Recode the MARST column in the census data
        census_df['MARST'] = census_df['MARST'].map(marital_status_map)

        #race census
        race_map = {
            1: 1,  # White -> White, Alone
            2: 2,  # Black/African American -> Black, Alone
            3: 4,  # American Indian or Alaska Native -> Any other race alone, or race in combination
            4: 3,  # Chinese -> Asian, Alone
            5: 3,  # Japanese -> Asian, Alone
            6: 3,  # Other Asian or Pacific Islander -> Asian, Alone
            7: 4,  # Other race, nec -> Any other race alone, or race in combination
            8: 4,  # Two major races -> Any other race alone, or race in combination
            9: 4   # Three or more major races -> Any other race alone, or race in combination
        }
        census_df['RACE'] = census_df['RACE'].map(race_map)

        educ_mapping = {
            0: 1,  # N/A or no schooling
            1: 1,  # Less than high school
            2: 1,  # Less than high school
            3: 1,  # Less than high school
            4: 1,  # Less than high school
            5: 1,  # Less than high school
            6: 2,  # High school graduate
            7: 3,  # Some college
            8: 3,  # Some college
            9: 3,  # Some college
            10: 4, # Bachelor's degree
            11: 5  # Graduate degree
        }

        # Recode the EDUC column in the census data
        census_df['EDUC'] = census_df['EDUC'].map(educ_mapping)

        #BIRTHYEAR just rename to AGE
        census_df.rename(columns={'BIRTHYR':'AGE'},inplace=True)

        relevant_columns_local = ['PERWT'] + relevant_columns_global
        #REGION,EDUC,INCTOT,SEX,MARST,FAMSIZE,RACE, BIRTHYR
        #deleting famsize because the categories are too different and BIDENPERC
        census_df = census_df.filter(items=relevant_columns_local)

    return survey_df, census_df