import pandas as pd


def filter_questions(input_file, output_file):
    '''
    input_file - str - path to axios-ipsos covid survey
    output_file - str - path to output file

    it simply keeps the columns named in "columns_to_keep" and deletes all other columns
    '''
    print(input_file)
    df = pd.read_csv(input_file, encoding="ISO-8859-1")
    
    columns_to_keep = [
    "wt_final", "Q107_1", "Q107_2", "Q107_3", "Q107_4", "ppreg4", "ppmsacat", 
    "ppeducat","ppinc7", "ppgender", "ppmarit5", 
    "pphhsize", "pprent", "ppethm"
    ]
    #"ppinc7"
    # Filter the DataFrame to keep only the specified columns
    df_filtered = df[columns_to_keep]
    # Save the cleaned data
    df_filtered.to_csv(output_file, index=False, encoding="ISO-8859-1")
    print(f"Filtered data saved to {output_file}")

def CPS_recoding_survey_and_census_data(survey_df, census_df):

    '''
    survey_df - pandas df - household census survey data
    census_df - pandas df - IPUMS survey 
    iterates over a survey df and census df and re-encodes all variables manually

    reincoding code was generated by CHATGPT
    '''
    state_code_to_biden_pct = {
        1: 0.3657,
        2: 0.4277,
        4: 0.4936,
        5: 0.3478,
        6: 0.6348,
        8: 0.5540,
        9: 0.5924,
        10: 0.5878,
        11: 0.9215,
        12: 0.4786,
        13: 0.4950,
        15: 0.6373,
        16: 0.3307,
        17: 0.5754,
        18: 0.4096,
        19: 0.4489,
        20: 0.4156,
        21: 0.3615,
        22: 0.3985,
        23: 0.5309,
        24: 0.6536,
        25: 0.6560,
        26: 0.5062,
        27: 0.5240,
        28: 0.4106,
        29: 0.4141,
        30: 0.4055,
        31: 0.3936,
        32: 0.5006,
        33: 0.5271,
        34: 0.5733,
        35: 0.5429,
        36: 0.6086,
        37: 0.4859,
        38: 0.3176,
        39: 0.4524,
        40: 0.3229,
        41: 0.5645,
        42: 0.5001,
        44: 0.5939,
        45: 0.4343,
        46: 0.3561,
        47: 0.3745,
        48: 0.4648,
        49: 0.3765,
        50: 0.6609,
        51: 0.5411,
        53: 0.5797,
        54: 0.2970,
        55: 0.4945,
        56: 0.2655
    }
    
    #drop all columns not prevelant to each survey
    YEAR = 2021
    relevant_columns_global = ['REGION', 'SEX', 'AGE']

    if survey_df is not None:
        #remove people that didnt answer vaccine question
        survey_df = survey_df[survey_df['ANYWORK'] != -99]
        survey_df = survey_df[survey_df['ANYWORK'] != -88]

        #income. only need to clean up -99 and -88 which are missing responses
        survey_df= survey_df[survey_df['INCOME'] != -99]
        survey_df= survey_df[survey_df['INCOME'] != -88]

        survey_df['EST_ST'] = survey_df['EST_ST'].map(state_code_to_biden_pct)

        def recode_anywork(value):
            if value == 2: #no
                return 0
            elif value == 1: #yes
                return 1
        
        survey_df['ANYWORK'] = survey_df['ANYWORK'].apply(recode_anywork)
        
        def recode_census_age(value):
            if YEAR - value >= 85: 
                return 5
            elif YEAR - value >= 65:
                return 4
            elif YEAR - value >= 50:
                return 3
            elif YEAR - value >= 35:
                return 2
            elif YEAR - value >= 18:
                return 1
        survey_df['TBIRTH_YEAR'] = survey_df['TBIRTH_YEAR'].apply(recode_census_age)

        #ipums chosen variables: REGION,EDUC,INCTOT,SEX,MARST,FAMSIZE,RACE, BIRTHYR
        #census corresponding: REGION, EEDUC, INCOME, EGENDER, MS, THHLD_NUMPER, RRACE, TBIRTH_YEAR

        #TBIRTH_YEAR just rename to AGE
        survey_df.rename(columns={'TBIRTH_YEAR':'AGE'},inplace=True)

        survey_df.rename(columns={'ANYWORK':'EMPLOYED'},inplace=True)
        #INCOME just rename to INCTOT
        survey_df.rename(columns={'INCOME':'INCTOT'},inplace=True)

        #EGENDER just rename to sex
        survey_df.rename(columns={'EGENDER':'SEX'},inplace=True)
        
        relevant_columns_local = ['PWEIGHT', 'EMPLOYED'] + relevant_columns_global

        #deleting famsize because the categories are too different
        survey_df = survey_df.filter(items=relevant_columns_local)

    if census_df is not None:
        census_df = census_df[census_df['MONTH'] == 5]
        census_df = census_df.dropna(subset=['EMPSTAT', 'REGION', 'SEX', 'AGE'])
        #clean any miszing birth years
        #remove anyone with birthyear born within 18 years of survey.
        census_df = census_df[census_df['AGE'] >= 18]
        #sex clean up missing values
        census_df= census_df[census_df['SEX'] != 9] 
        #education. remove missing entries before mapping
        census_df = census_df[census_df['EDUC'] != 99] 
        # REGION,EDUC,INCTOT,SEX,MARST,FAMSIZE,RACE,BIRTHYR
        def recode_census_age(value):
            if value >= 85: 
                return 5
            elif value >= 65:
                return 4
            elif value >= 50:
                return 3
            elif value >= 35:
                return 2
            elif value >= 18:
                return 1
        census_df['AGE'] = census_df['AGE'].apply(recode_census_age)

        def recode_census_region(value):
            if 10 <= value <= 19:
                return 1  # NorthEast
            elif 20 <= value <= 29:
                return 3  # MidWest
            elif 30 <= value <= 39:
                return 2  # South
            elif 40 <= value <= 49:
                return 4  # West
            else:
                return None  # Handle unexpected values
        # Apply the recoding function to the region column in the census data
        census_df['REGION'] = census_df['REGION'].apply(recode_census_region)


        def map_income(value):
            if value == -99:
                return -99  # Question seen but not selected
            elif value == -88:
                return -88  # Missing / Did not report
            elif value < 25000:
                return 1  # Less than $25,000
            elif 25000 <= value < 35000:
                return 2  # $25,000 - $34,999
            elif 35000 <= value < 50000:
                return 3  # $35,000 - $49,999
            elif 50000 <= value < 75000:
                return 4  # $50,000 - $74,999
            elif 75000 <= value < 100000:
                return 5  # $75,000 - $99,999
            elif 100000 <= value < 150000:
                return 6  # $100,000 - $149,999
            elif 150000 <= value < 200000:
                return 7  # $150,000 - $199,999
            else:
                return 8  # $200,000 and above

        census_df['INCTOT'] = census_df['INCTOT'].apply(map_income)
        
        def encode_employment(value):
            if value == 10:
                return 1
            else:
                return 0
        census_df['EMPSTAT'] = census_df['EMPSTAT'].apply(encode_employment)

        census_df.rename(columns={'WTFINL':'PERWT'},inplace=True)
        census_df.rename(columns={'EMPSTAT':'EMPLOYED'},inplace=True)

        relevant_columns_local = ['PERWT', 'EMPLOYED'] + relevant_columns_global
        #REGION,EDUC,INCTOT,SEX,MARST,FAMSIZE,RACE, BIRTHYR
        #deleting famsize because the categories are too different and BIDENPERC
        census_df = census_df.filter(items=relevant_columns_local)

    return survey_df, census_df

if __name__ == "__main__":
    pass