# -*- coding: utf-8 -*-
"""gan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JuKmTrwUWn2i3gTH96Aku3FAptxSE-zH
"""

import torch
import random
import copy
import numpy as np
import torch.nn.functional as F
from torch import nn, optim
from tqdm import tqdm

class Generator(nn.Module):
    def __init__(self, input_size, bias_size, temperature=0.1):
        super(Generator, self).__init__()
        self.linear = nn.Linear(input_size, 1)
        torch.nn.init.xavier_uniform_(self.linear.weight) 
        #if self.linear.bias is not None:
        #    torch.nn.init.zeros_(self.linear.bias)
        '''
        modules = []
        modules.append(nn.Linear(input_size,256))
        modules.append(nn.LeakyReLU())
        modules.append(nn.Dropout(0.1))
        modules.append(nn.Linear(256,1))
        self.linear = nn.Sequential(*modules)
        for layer_id, layer in enumerate(self.linear):
            #initialize all intermediary layers using relu non linearity
            if isinstance(layer, torch.nn.Linear) and layer_id+1 < len(self.linear):
                if isinstance(self.linear[layer_id+1], torch.nn.LeakyReLU):  # Apply He initialization to Linear layers
                    torch.nn.init.kaiming_uniform_(layer.weight, mode='fan_out', nonlinearity='leaky_relu')  # or kaiming_uniform_
                elif isinstance(self.linear[layer_id+1], torch.nn.Identity):
                    torch.nn.init.xavier_uniform_(layer.weight) 
                if layer.bias is not None:
                    torch.nn.init.zeros_(layer.bias)  # Initialize biases to 0        
        '''
        self.bias_size = bias_size
        self.temperature = temperature

    def forward(self, input):
        logits = None
        logit = self.linear(input).transpose(0,1)
        for _ in range(self.bias_size):
            if logits == None:
                logits = logit
            else:
                logits = torch.cat((logits, logit), dim=0)
        matrix = F.gumbel_softmax(logits, tau=self.temperature, hard=False) # give index
        output = torch.matmul(matrix, input)
        with torch.no_grad():
            max_indices = torch.argmax(matrix, dim=1)
        return output, max_indices, matrix
    
    def generate_samples(self, data, num_samples=5, repeat=False, test_avgs = False):
        input = copy.deepcopy(data)
        outputs, max_indices = None, None
        avgs = []
        logits = self.linear(input).transpose(0,1)
        for _ in range(num_samples):
            matrix = F.gumbel_softmax(logits, tau=self.temperature, hard=False)
            with torch.no_grad():
                max_index = torch.argmax(matrix, dim=1)
                output = input[max_index]
            if outputs == None:
                outputs = output#.unsqueeze(dim=0)
            else:
                outputs = torch.cat((outputs, output), dim = 0)
            if not repeat:
                logits = torch.cat((logits[:, :max_index], logits[:, max_index+1:]), dim = 1) 
                input = torch.cat((input[:max_index], input[max_index+1:]), dim = 0)    
            if test_avgs:
                avg = outputs[:, -1].mean().cpu().detach().item()
                avgs.append(avg)
        if test_avgs:
            return outputs, avgs
        else:
            return outputs

    def test(self, input):
        logit = self.linear(input).transpose(0,1)
        output = nn.Softmax(dim=1)(logit)
        return output
    
    def Shannon_entropy(self, prob_vector):
        epsilon = 1e-10
        return -torch.sum(prob_vector * torch.log(prob_vector + epsilon))

class Disctiminator(nn.Module):
    def __init__(self, input_size):
        super(Disctiminator, self).__init__()
        self.num_hidden = 512
        self.linear1 = nn.Linear(input_size, self.num_hidden)
        self.dropout1 = nn.Dropout(0.2)
        self.activation1 = nn.LeakyReLU()
        self.linear2 = nn.Linear(self.num_hidden, self.num_hidden)
        self.dropout2 = nn.Dropout(0.2)
        self.activation2 = nn.LeakyReLU()
        self.linear3 = nn.Linear(self.num_hidden, 1)
        self.dropout3 = nn.Dropout(0.2)
        self.activation3 = nn.LeakyReLU()

    def forward(self, input):
        output = self.linear1(input)
        output = self.dropout1(output)
        #output = self.activation1(output)
        output = self.linear2(output)
        output = self.dropout2(output)
        #output = self.activation2(output)
        output = self.linear3(output)
        output = self.dropout3(output)
        #output = self.activation3(output)
        return output

class GAN():

    def __init__(self, dataset, lr, truth_size, bias_size, temperature, epochs, batch_in_epoch, generator_training_factor, discriminator_training_factor, device):
            
        ground_truth_dataset, bias_dataset = dataset.get_dataset()
        self.ground_truth_dataset = torch.tensor(ground_truth_dataset).to(device)
        self.bias_dataset = torch.tensor(bias_dataset)[:, :-1].to(device)
        self.label = torch.tensor(bias_dataset)[:, -1].to(device)
        #self.real_target = self.ground_truth_dataset[:, -1].mean().cpu().detach().item()

        input_size = dataset.get_dim()
        self.generator = Generator(input_size, bias_size, temperature).to(device)
        self.discriminator = Disctiminator(input_size).to(device)
        self.lr = lr
        self.generator_optimizer = torch.optim.Adam(self.generator.parameters(), lr=self.lr)
        self.discriminator_optimizer = torch.optim.Adam(self.discriminator.parameters(), lr=self.lr)
        self.loss_function = nn.BCEWithLogitsLoss()
        self.truth_size = truth_size
        self.temperature = temperature
        self.epochs = epochs
        self.batch_in_epoch = batch_in_epoch
        self.generator_training_factor = generator_training_factor
        self.discriminator_training_factor = discriminator_training_factor
        self.device = device

    def generate_data(self):
        index = random.sample(range(len(self.ground_truth_dataset)), self.truth_size)
        return self.ground_truth_dataset[index]
    
    '''
    def distance2target(self, num_batches):
        distances = []
        for _ in range(num_batches):
            _, indices, _ = self.generator(self.bias_dataset)
            indices = indices.cpu().detach().numpy()
            pred_target = self.bias_dataset[indices, -1].mean().cpu().detach().item()
            distances.append((pred_target-self.real_target)**2)
        return np.mean(distances)
    '''
    
    def top_domination(self, top_n = 5):
        prob_vector = self.generator.test(self.bias_dataset)
        top_values, _ = torch.topk(prob_vector, k=top_n, dim=1)
        top_sum = top_values.sum()
        return top_sum.item()

    def train_generator(self):

        bias_data, _, prob_matrix = self.generator(self.bias_dataset)
        bias_label = self.discriminator(bias_data.to(self.device))
        generator_loss = self.loss_function(bias_label, torch.ones_like(bias_label).to(self.device))
        entropy = self.generator.Shannon_entropy(prob_matrix)
        generator_loss -= 1e-5 * entropy 

        self.generator_optimizer.zero_grad()
        generator_loss.backward()
        self.generator_optimizer.step()

        return generator_loss.item()

    def train_discriminator(self):

        ground_truth_data = self.generate_data()
        ground_truth_label = self.discriminator(ground_truth_data)
        bias_data, _, _ = self.generator(self.bias_dataset)
        bias_label = self.discriminator(bias_data.to(self.device))

        label_pred = torch.cat((ground_truth_label, bias_label), dim=0).to(self.device)
        label_true = torch.cat((torch.ones_like(ground_truth_label), torch.zeros_like(bias_label)), dim=0).to(self.device)
        indices = torch.randperm(label_pred.size(0))
        label_pred = label_pred[indices]
        label_true = label_true[indices]
        discriminator_loss = self.loss_function(label_pred, label_true.to(self.device))

        self.discriminator_optimizer.zero_grad()
        discriminator_loss.backward(retain_graph=True)
        self.discriminator_optimizer.step()

        return discriminator_loss.item()

    def onestep_train(self, generator_training_factor=1, discriminator_training_factor=1):

        generator_losses = []
        discriminator_losses = []
        for _ in range(generator_training_factor):
            generator_loss = self.train_generator()
            generator_losses.append(generator_loss)

        for _ in range(discriminator_training_factor):
            discriminator_loss = self.train_discriminator()
            discriminator_losses.append(discriminator_loss)

        return generator_losses, discriminator_losses

    def train(self):

        #distances = []
        #top5_dominations = []
        predicts = []
        generator_losses, discriminator_losses = [], []

        for epoch in tqdm(range(self.epochs)):
            for i_batch in range(self.batch_in_epoch):
                generator_losses_1ep, discriminator_loss_1ep = self.onestep_train(generator_training_factor=self.generator_training_factor, 
                                                                                  discriminator_training_factor=self.discriminator_training_factor)
            #distance = self.distance2target(5)
            #distances.append(distance)
            #top5_domination = self.top_domination(5)
            #top5_dominations.append(top5_domination)
            generator_losses += generator_losses_1ep
            discriminator_losses += discriminator_loss_1ep

            predicts.append(self.predict(5))

        #return distances, generator_losses, discriminator_losses, top5_dominations
        return generator_losses, discriminator_losses, predicts

    def predict(self, num_batches):
        predicts = []
        for _ in range(num_batches):
            _, indices, _ = self.generator(self.bias_dataset)
            indices = indices.cpu().detach().numpy()
            pred_target = self.label[indices].mean().cpu().detach().item()
            predicts.append(pred_target)
        return np.mean(predicts)        

    def save_gan(self, folder_path):
        torch.save(self.generator.state_dict(), folder_path+"/generator.pt")
        torch.save(self.discriminator.state_dict(), folder_path+"/discriminator.pt")

    def load_gan(self, folder_path):
        self.generator.load_state_dict(torch.load(folder_path+"/generator.pt", weights_only=True))
        self.generator.eval()
        self.discriminator.load_state_dict(torch.load(folder_path+"/discriminator.pt", weights_only=True))
        self.discriminator.eval()

    def one_by_one_test(self, num_samples, repeat = False):
        samples, avgs = self.generator.generate_samples(self.bias_dataset, num_samples, repeat, True)
        return avgs

if __name__ == "__main__":
    dataset1 = [[1,2],[2,2],[3,2]]
    dataset2 = [[5,4],[5,5],[5,6]]
    dataset3 = [[1,2],[2,2],[3,2],[5,4],[5,5],[5,6]]
    dataset = [dataset1, dataset2]
    dataset1 = torch.tensor(dataset1, dtype = torch.float32)
    dataset2 = torch.tensor(dataset2, dtype = torch.float32)
    dataset3 = torch.tensor(dataset3, dtype = torch.float32)
    dataset = torch.tensor(dataset, dtype = torch.float32) 
    generator = Generator(2, 5)
    a = generator.test(dataset3)
    print(a)
    #print(generator.generate_one_sample(dataset2))
    #print(generator.generate_samples(dataset))
    #print(generator.generate_samples(dataset1))
    #print(generator.generate_samples(dataset3, 6))
